MACRO(LINK_WITH_VARIABLES TARGET_NAME)
    FOREACH(LIBRARY_VAR ${ARGN})
        IF(NOT ${LIBRARY_VAR})
            SET(LIBRARY_RELEASE_VAR ${LIBRARY_VAR}_RELEASE)
            SET(LIBRARY_DEBUG_VAR   ${LIBRARY_VAR}_DEBUG)
            
            IF(${LIBRARY_RELEASE_VAR} OR ${LIBRARY_DEBUG_VAR})
                SET(${LIBRARY_VAR} "")
                IF(NOT ${LIBRARY_RELEASE_VAR})
                    SET(${LIBRARY_VAR} ${${LIBRARY_DEBUG_VAR}})
                ELSEIF(NOT ${LIBRARY_DEBUG_VAR})
                    SET(${LIBRARY_VAR} ${${LIBRARY_RELEASE_VAR}})
                ELSE(NOT ${LIBRARY_RELEASE_VAR})
                    SET(${LIBRARY_VAR} optimized ${${LIBRARY_RELEASE_VAR}} debug ${${LIBRARY_DEBUG_VAR}})
                ENDIF(NOT ${LIBRARY_RELEASE_VAR})
            ELSE(${LIBRARY_RELEASE_VAR} OR ${LIBRARY_DEBUG_VAR})
                MESSAGE(FATAL_ERROR "${TARGET_NAME} links against ${LIBRARY_VAR}, but this module is not found. Please check that you added the corresponing find_package().")
            ENDIF(${LIBRARY_RELEASE_VAR} OR ${LIBRARY_DEBUG_VAR})
        ENDIF(NOT ${LIBRARY_VAR})
        TARGET_LINK_LIBRARIES(${TARGET_NAME} ${${LIBRARY_VAR}})
    ENDFOREACH(LIBRARY_VAR)
ENDMACRO(LINK_WITH_VARIABLES TARGET_NAME)

MACRO(LINK_INTERNAL TARGET_NAME)
    TARGET_LINK_LIBRARIES(${TARGET_NAME} ${ARGN})
ENDMACRO(LINK_INTERNAL TARGET_NAME)

MACRO(LINK_EXTERNAL TARGET_NAME)
    FOREACH(LINKLIB ${ARGN})
        TARGET_LINK_LIBRARIES(${TARGET_NAME} "${LINKLIB}" )
    ENDFOREACH(LINKLIB)
ENDMACRO(LINK_EXTERNAL TARGET_NAME)

MACRO(SETUP_LINK_LIBRARIES)
    message(FATAL_ERROR Stop)
    SET(TARGET_LIBRARIES ${TARGET_COMMON_LIBRARIES})

    FOREACH(LINKLIB ${TARGET_ADDED_LIBRARIES})
      SET(TO_INSERT TRUE)
      FOREACH (value ${TARGET_COMMON_LIBRARIES})
            IF (${value} STREQUAL ${LINKLIB})
                  SET(TO_INSERT FALSE)
            ENDIF (${value} STREQUAL ${LINKLIB})
        ENDFOREACH (value ${TARGET_COMMON_LIBRARIES})
      IF(TO_INSERT)
          LIST(APPEND TARGET_LIBRARIES ${LINKLIB})
      ENDIF(TO_INSERT)
    ENDFOREACH(LINKLIB)

#    FOREACH(LINKLIB ${TARGET_LIBRARIES})
#            TARGET_LINK_LIBRARIES(${TARGET_TARGETNAME} optimized ${LINKLIB} debug "${LINKLIB}${CMAKE_DEBUG_POSTFIX}")
#    ENDFOREACH(LINKLIB)
        LINK_INTERNAL(${TARGET_TARGETNAME} ${TARGET_LIBRARIES})
    FOREACH(LINKLIB ${TARGET_EXTERNAL_LIBRARIES})
            TARGET_LINK_LIBRARIES(${TARGET_TARGETNAME} ${LINKLIB})
    ENDFOREACH(LINKLIB)
    IF(TARGET_LIBRARIES_VARS)
        LINK_WITH_VARIABLES(${TARGET_TARGETNAME} ${TARGET_LIBRARIES_VARS})
    ENDIF(TARGET_LIBRARIES_VARS)

ENDMACRO(SETUP_LINK_LIBRARIES)

MACRO(SETUP_SHARED TARGET_NAME)

    IF(NOT TARGET_TARGETNAME)
        SET(TARGET_TARGETNAME "${TARGET_DEFAULT_PREFIX}${TARGET_NAME}")
    ENDIF(NOT TARGET_TARGETNAME)

    IF(NOT TARGET_LABEL)
        SET(TARGET_LABEL "${TARGET_DEFAULT_LABEL_PREFIX} ${TARGET_NAME}")
    ENDIF(NOT TARGET_LABEL)

    QT5_WRAP_UI(TARGET_UI_HEADERS ${TARGET_UIS})
    QT5_WRAP_CPP(TARGET_MOC_SOURCES ${TARGET_MOC_HEADERS})
    QT5_ADD_RESOURCES(TARGET_QRC_SOURCES ${TARGET_QRC})

    SOURCE_GROUP("QML Files" FILES ${TARGET_QML})
    SOURCE_GROUP("Resources" FILES ${TARGET_QRC})
    SOURCE_GROUP("Forms" FILES ${TARGET_UIS})
    SOURCE_GROUP("Generated Files" FILES ${TARGET_QRC_SOURCES} ${TARGET_MOC_SOURCES} ${TARGET_UI_HEADERS})

    ADD_LIBRARY(${TARGET_TARGETNAME} SHARED
                ${TARGET_HEADERS} ${TARGET_SOURCES}
                ${TARGET_QRC} ${TARGET_QRC_SOURCES}
                ${TARGET_QML}
                ${TARGET_MOC_HEADERS} ${TARGET_MOC_SOURCES}
                ${TARGET_UIS} ${TARGET_UI_HEADERS}
    )

    SET_TARGET_PROPERTIES(${TARGET_TARGETNAME} PROPERTIES PROJECT_LABEL "${TARGET_LABEL}")
 
    SETUP_LINK_LIBRARIES()

    INSTALL(TARGETS ${TARGET_TARGETNAME}
                RUNTIME DESTINATION ./bin 
                LIBRARY DESTINATION ./bin
                ARCHIVE DESTINATION ./bin)

ENDMACRO(SETUP_SHARED)

MACRO(SETUP_EXE IS_COMMANDLINE_APP)

    IF(NOT TARGET_TARGETNAME)
        SET(TARGET_TARGETNAME "${TARGET_DEFAULT_PREFIX}${TARGET_NAME}")
        MESSAGE(STATUS "TARGET_TARGETNAME=${TARGET_TARGETNAME}")
    ENDIF(NOT TARGET_TARGETNAME)

    IF(NOT TARGET_LABEL)
            SET(TARGET_LABEL "${TARGET_DEFAULT_LABEL_PREFIX} ${TARGET_NAME}")
    ENDIF(NOT TARGET_LABEL)

    QT5_WRAP_UI(TARGET_UI_HEADERS ${TARGET_UIS})
    QT5_WRAP_CPP(TARGET_MOC_SOURCES ${TARGET_MOC_HEADERS})
    QT5_ADD_RESOURCES(TARGET_QRC_SOURCES ${TARGET_QRC})

    SOURCE_GROUP("QML Files" FILES ${TARGET_QML})
    SOURCE_GROUP("Resources" FILES ${TARGET_QRC})
    SOURCE_GROUP("Forms" FILES ${TARGET_UIS})
    SOURCE_GROUP("Generated Files" FILES ${TARGET_QRC_SOURCES} ${TARGET_MOC_SOURCES} ${TARGET_UI_HEADERS})

    IF(NOT ${IS_COMMANDLINE_APP})
        IF(WIN32)
            SET(PLATFORM_SPECIFIC_CONTROL WIN32)
        ENDIF(WIN32)
    ENDIF(NOT ${IS_COMMANDLINE_APP})
    
    ADD_EXECUTABLE(${TARGET_TARGETNAME} ${PLATFORM_SPECIFIC_CONTROL}
                   ${TARGET_HEADERS} ${TARGET_SOURCES}
                   ${TARGET_QRC} ${TARGET_QRC_SOURCES}
                   ${TARGET_QML}
                   ${TARGET_MOC_HEADERS} ${TARGET_MOC_SOURCES}
                   ${TARGET_UIS} ${TARGET_UI_HEADERS}
    )
    TARGET_LINK_LIBRARIES(${TARGET_TARGETNAME} Qt5::WinMain)

    SET_TARGET_PROPERTIES(${TARGET_TARGETNAME} PROPERTIES PROJECT_LABEL "${TARGET_LABEL}")
    SET_TARGET_PROPERTIES(${TARGET_TARGETNAME} PROPERTIES DEBUG_POSTFIX "${CMAKE_DEBUG_POSTFIX}")
    
    SETUP_LINK_LIBRARIES()
        
    INSTALL(TARGETS ${TARGET_TARGETNAME}
            RUNTIME DESTINATION ./bin 
            LIBRARY DESTINATION ./bin
            ARCHIVE DESTINATION ./bin)

ENDMACRO(SETUP_EXE)

MACRO(SETUP_APPLICATION APPLICATION_NAME)
    SET(TARGET_NAME ${APPLICATION_NAME} )
    IF(${ARGC} GREATER 1)
        SET(IS_COMMANDLINE_APP ${ARGV1})
    ELSE(${ARGC} GREATER 1)
        SET(IS_COMMANDLINE_APP 0)
    ENDIF(${ARGC} GREATER 1)
    SETUP_EXE(${IS_COMMANDLINE_APP})
ENDMACRO(SETUP_APPLICATION)

MACRO(SETUP_COMMANDLINE_APPLICATION APPLICATION_NAME)
    SETUP_APPLICATION(${APPLICATION_NAME} 1)
ENDMACRO(SETUP_COMMANDLINE_APPLICATION)